# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Attribute
version:      0.01
version_from: lib/File/Attribute.pm
installdirs:  site
requires:
    Exporter:                      0
    File::Slurp::SmallFile:        0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
